# Active profile set externally (recommended)
# Example:
# mvn spring-boot:run -Dspring-boot.run.profiles=local

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Springdoc
springdoc.show-actuator=false

# Server
server.port=8080