spring.application.name=backend
springdoc.show-actuator=false
spring.datasource.url=jdbc:postgresql://localhost:5432/jobtrakr
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.profiles.active=local